version: '3.7'
services:
    database:
        image: 'mysql:latest'
        container_name: mate
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'
        volumes:
            - ./data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_mate
        restart: always
        depends_on:
          - database
        ports:
          - "9999:80"
        environment: 
            PMA_HOST: db

    php:
      build: .
      container_name: hare_mate
      ports:
          - "8888:80"
      depends_on:
          - database
      volumes:
          - ./docker/vhosts:/etc/apache2/sites-enabled
          - ./app:/var/www
      restart: always

